//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPractice2211.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int Basket_Id { get; set; }
        public int Material_Id { get; set; }
        public int User_Id { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual User User { get; set; }
    }
}
