//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDPractice2211.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Recept_Id { get; set; }
    
        public virtual Recept Recept { get; set; }
    }
}
